<?php

namespace Randock\PostNL\BulkMailApi;

/**
 * Class which returns the class map definition
 * @package
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get()
    {
        return array(
            'TenderBulkMailOrderV2' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\TenderBulkMailOrderV2',
            'TenderBulkMailOrderV2Response' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\TenderBulkMailOrderV2Response',
            'PreAdviceBulkMailOrderV2' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\PreAdviceBulkMailOrderV2',
            'PreAdviceBulkMailOrderV2Response' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\PreAdviceBulkMailOrderV2Response',
            'ValidateAddressAttachmentV1' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ValidateAddressAttachmentV1',
            'ValidateAddressAttachmentV1Response' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ValidateAddressAttachmentV1Response',
            'GetValidationResultV1' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\GetValidationResultV1',
            'GetValidationResultV1Response' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\GetValidationResultV1Response',
            'ValidateAndSortAddressAttachmentV1' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ValidateAndSortAddressAttachmentV1',
            'ValidateAndSortAddressAttachmentV1Response' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ValidateAndSortAddressAttachmentV1Response',
            'GetValidationAndSortingResultV1' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\GetValidationAndSortingResultV1',
            'GetValidationAndSortingResultV1Response' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\GetValidationAndSortingResultV1Response',
            'GetPackagingInformationV1' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\GetPackagingInformationV1',
            'GetPackagingInformationV1Response' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\GetPackagingInformationV1Response',
            'Business2BusinessContainerV2' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\Business2BusinessContainerV2',
            'ArrayOfBulkmailOrderType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfBulkmailOrderType',
            'BulkmailOrderType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\BulkmailOrderType',
            'HeaderType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\HeaderType',
            'ArrayOfDocumentIDType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfDocumentIDType',
            'DocumentIDType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\DocumentIDType',
            'IdentifierType1' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\IdentifierType1',
            'IdentifierType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\IdentifierType',
            'OpenAttachmentType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\OpenAttachmentType',
            'SemanticAttachmentType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\SemanticAttachmentType',
            'AttachmentBaseType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\AttachmentBaseType',
            'ArrayOfDescriptionType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfDescriptionType',
            'DescriptionType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\DescriptionType',
            'TextType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\TextType',
            'CodeType1' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\CodeType1',
            'CodeType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\CodeType',
            'BinaryObjectType1' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\BinaryObjectType1',
            'BinaryObjectType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\BinaryObjectType',
            'NameType1' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\NameType1',
            'NameType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\NameType',
            'QuantityType1' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\QuantityType1',
            'QuantityType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\QuantityType',
            'ArrayOfCodeType1' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfCodeType1',
            'ArrayOfNoteType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfNoteType',
            'NoteType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\NoteType',
            'ArrayOfTextType1' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfTextType1',
            'TextType1' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\TextType1',
            'UserAreaType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\UserAreaType',
            'ArrayOfConsignmentType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfConsignmentType',
            'ConsignmentType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ConsignmentType',
            'ConsignmentContractType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ConsignmentContractType',
            'ConsignmentPhysicalDataType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ConsignmentPhysicalDataType',
            'MeasureType1' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\MeasureType1',
            'MeasureType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\MeasureType',
            'ArrayOfIdentifierType1' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfIdentifierType1',
            'ArrayOfTrackingIDRangeType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfTrackingIDRangeType',
            'TrackingIDRangeType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\TrackingIDRangeType',
            'ConsignmentProcessingType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ConsignmentProcessingType',
            'TimePeriodType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\TimePeriodType',
            'TimePeriodABIEType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\TimePeriodABIEType',
            'ConsignmentDeliveryWeekType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ConsignmentDeliveryWeekType',
            'ArrayOfCharacteristicType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfCharacteristicType',
            'CharacteristicType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\CharacteristicType',
            'CountryCodeType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\CountryCodeType',
            'CustomerConsignmentType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\CustomerConsignmentType',
            'ArrayOfConsignmentAdministrativeReferencesType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfConsignmentAdministrativeReferencesType',
            'ConsignmentAdministrativeReferencesType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ConsignmentAdministrativeReferencesType',
            'ArrayOfItemIDType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfItemIDType',
            'ItemIDType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ItemIDType',
            'CustomerPartyType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\CustomerPartyType',
            'PayerPartyBaseType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\PayerPartyBaseType',
            'PartyBaseType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\PartyBaseType',
            'ArrayOfContactType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfContactType',
            'ContactType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ContactType',
            'SemanticContactType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\SemanticContactType',
            'ContactABIEType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ContactABIEType',
            'ArrayOfAddressType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfAddressType',
            'AddressType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\AddressType',
            'AddressBaseType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\AddressBaseType',
            'ArrayOfNameType1' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfNameType1',
            'ArrayOfCountrySubDivisionCodeType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfCountrySubDivisionCodeType',
            'CountrySubDivisionCodeType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\CountrySubDivisionCodeType',
            'ArrayOfItemsChoiceType1' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfItemsChoiceType1',
            'ArrayOfPreferenceType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfPreferenceType',
            'PreferenceType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\PreferenceType',
            'PreferenceABIEType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\PreferenceABIEType',
            'StatusType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\StatusType',
            'StatusABIEType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\StatusABIEType',
            'StatusBasisType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\StatusBasisType',
            'ArrayOfSequencedTextType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfSequencedTextType',
            'SequencedTextType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\SequencedTextType',
            'ArrayOfEMailAddressCommunicationType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfEMailAddressCommunicationType',
            'EMailAddressCommunicationType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\EMailAddressCommunicationType',
            'ArrayOfTelephoneCommunicationType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfTelephoneCommunicationType',
            'TelephoneCommunicationType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\TelephoneCommunicationType',
            'ArrayOfElectronicCommunicationType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfElectronicCommunicationType',
            'ElectronicCommunicationType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ElectronicCommunicationType',
            'ArrayOfLocationType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfLocationType',
            'LocationType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\LocationType',
            'LocationABIEType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\LocationABIEType',
            'CoordinateType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\CoordinateType',
            'CoordinateBaseType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\CoordinateBaseType',
            'ArrayOfItemsChoiceType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfItemsChoiceType',
            'PartyIDsType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\PartyIDsType',
            'BankAccountType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\BankAccountType',
            'ShippingPartyType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ShippingPartyType',
            'ArrayOfStatusType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfStatusType',
            'WorkLocationType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\WorkLocationType',
            'ArrayOfContactPersonType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfContactPersonType',
            'ContactPersonType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ContactPersonType',
            'NamePersonType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\NamePersonType',
            'ArrayOfPreferredNameType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfPreferredNameType',
            'PreferredNameType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\PreferredNameType',
            'ArrayOfWorkLocationAddressType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfWorkLocationAddressType',
            'WorkLocationAddressType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\WorkLocationAddressType',
            'AddressTypeType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\AddressTypeType',
            'WorkLocationTypeType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\WorkLocationTypeType',
            'MessageHeaderType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\MessageHeaderType',
            'BusinessDocumentMessageHeader' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\BusinessDocumentMessageHeader',
            'ArrayOfBusinessScope' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfBusinessScope',
            'BusinessScope' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\BusinessScope',
            'BusinessScopeID' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\BusinessScopeID',
            'BusinessScopeInstanceID' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\BusinessScopeInstanceID',
            'BusinessScopeTypeCode' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\BusinessScopeTypeCode',
            'BusinessDocumentMessageID' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\BusinessDocumentMessageID',
            'ArrayOfBusinessDocumentMessageHeaderParty' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfBusinessDocumentMessageHeaderParty',
            'BusinessDocumentMessageHeaderParty' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\BusinessDocumentMessageHeaderParty',
            'BusinessDocumentMessageHeaderPartyContactPerson' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\BusinessDocumentMessageHeaderPartyContactPerson',
            'ArrayOfEmailURI' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfEmailURI',
            'EmailURI' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\EmailURI',
            'ArrayOfPhoneNumber' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfPhoneNumber',
            'PhoneNumber' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\PhoneNumber',
            'MEDIUM_Name' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\MEDIUM_Name',
            'ContactPersonInternalID' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ContactPersonInternalID',
            'PartyInternalID' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\PartyInternalID',
            'ArrayOfPartyStandardID' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfPartyStandardID',
            'PartyStandardID' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\PartyStandardID',
            'UUID' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\UUID',
            'Message' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\Message',
            'ArrayOfResult' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfResult',
            'Result' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\Result',
            'AddressAttachmentType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\AddressAttachmentType',
            'ArrayOfExtraAttachmentType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfExtraAttachmentType',
            'ExtraAttachmentType' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\ExtraAttachmentType',
            'ArrayOfXmlElement' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfXmlElement',
            'XmlElement' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\XmlElement',
            'ArrayOfanyType' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfanyType',
            'ArrayOfstring' => '\\Randock\\PostNL\\BulkMailApi\\ArrayType\\ArrayOfstring',
            'B2BAddressContainerV1' => '\\Randock\\PostNL\\BulkMailApi\\StructType\\B2BAddressContainerV1',
        );
    }
}
